spring:
    # Set the active profile (this will read the appropriate values for the environment)
    profiles:
        active: H2
server:
    port: 8081
---
########################
#
# H2 PROFILE
#
########################
spring:
  profiles: H2
  datasource:
    driver-class-name: org.h2.Driver
    password: ''
    url: jdbc:h2:mem:bootapp;DB_CLOSE_DELAY=-1
    username: sa
  h2:
    console:
      enabled: true
      

Hibernate:
    dialect: org.hibernate.dialect.H2Dialect
    defaultSchema:
    formatSql: false
    showSql: false
    useSqlComments: true
    buildDBFromHibernate: true
    startTCPServer: true    
    
logging:
    level:
        org.springframework: INFO
        org.hibernate: INFO
        com.zaxxer: INFO

---
########################
#
# MySQL PROFILE
#
########################
spring:
  profiles: MySQL
  datasource:
    driver-class-name: org.h2.Driver
    password: ''
    url: jdbc:h2:mem:bootapp;DB_CLOSE_DELAY=-1
    username: sa
  h2:
    console:
      enabled: true

Hibernate:
    dialect: org.hibernate.dialect.MySQL
    defaultSchema:
    formatSql: false
    showSql: false
    useSqlComments: true
    buildDBFromHibernate: true
    startTCPServer: true    
    
logging:
    level:
        org.springframework: INFO
        org.hibernate: INFO
        com.zaxxer: INFO     